// AUTH TYPES
export const USER_LOADED = 'USER_LOADED';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const CHANGED_PASSWORD = 'CHANGED_PASSWORD';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const AUTH_ERROR = 'AUTH_ERROR';

// POST TYPES
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_POST = 'GET_POST';
export const UPDATE_POST_LIKE = 'UPDATE_POST_LIKE';
export const CREATE_POST = 'CREATE_POST';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';
export const POST_ERROR = 'POST_ERROR';

// COMMENT TYPES
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_COMMENT_LIKES = 'UPDATE_COMMENT_LIKES';
export const REPLY_ON_COMMENT = 'REPLY_ON_COMMENT';
export const DELETE_REPLY = 'DELETE_REPLY';
export const UPDATE_REPLY_LIKES = 'UPDATE_REPLY_LIKES';